name: apply
  on:
    workflow_call:
      inputs:
        environment:
          required: true
          type: string
jobs: 
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Read terraform version 
        id: read-version
        run: |
          echo "TERRAFORM_VERSION=`cat ../.terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        run: |
          ./terraform.sh init ${{ inputs.environment }}

      - name: Terraform Apply
        id: apply
        run: |
          ./terraform.sh apply ${{ inputs.environment }} -auto-approve