name: "Terraform-Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        default: uat
        required: true 
        options:
        - dev
        - uat

defaults:
  run:
    shell: bash
    working-directory: src/main

jobs:
  terraform:
    # if: ${{ inputs.environment }} != null
    name: "terraform-apply"
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    environment: uat
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply
        
        uses: ./.github/workflows/terraform-apply-wf.yml
        with:
          environment: uat
          AWS_REGION: eu-south-1
          IAM_ROLE: ${{ secrets.IAM_ROLE}}