name: "Terraform-Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        default: uat
        required: true 
        options:
        - dev
        - uat


jobs:
  terraform:
    # if: ${{ inputs.environment }} != null
    name: "terraform-apply"
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    environment: uat

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_REGION: eu-south-1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Apply
        uses: ./.github/workflows/apply
        with:
          env: uat
          working-directory: src/main
