name: "Terraform-Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        default: uat
        required: true 
        options:
        - dev
        - uat

defaults:
  run:
    shell: bash
    working-directory: src/main

jobs:
  terraform:
    # if: ${{ inputs.environment }} != null
    uses: pagopa/personal-data-vault-infra/.github/workflows/terraform-apply-wf.yml@main
    with:
      environment: uat
      AWS_REGION: eu-south-1
    secrets: inherit